import { existsSync } from "node:fs";
import "node:process";

// Load the local .env in dev/test (existing vars win, dotenv-style).
// Vercel injects env vars directly and ships no .env file — skip when
// absent, since loadEnvFile throws if the file is missing.
if (existsSync(".env")) process.loadEnvFile(".env");

const env = process.env;

// In tests, outbound network is forbidden: the suite must mock every
// external service (DeepSeek, Resend, OSRM/Nominatim, map tiles) rather than
// call it live. Localhost requests — the spawned test server and the MCP
// endpoint — still pass. Dev and production are unaffected. Guarding here
// (not in the test setup) reaches the spawned app server too, whose browser
// tests otherwise share the process env and would hit live services.
if (env.NODE_ENV === "test") {
  const realFetch = globalThis.fetch.bind(globalThis);
  globalThis.fetch = ((
    input: Parameters<typeof fetch>[0],
    init?: Parameters<typeof fetch>[1],
  ) => {
    const url =
      typeof input === "string"
        ? input
        : input instanceof URL
          ? input.href
          : input.url;
    const host = new URL(url, "http://localhost").hostname;
    if (!["localhost", "127.0.0.1", "::1"].includes(host)) {
      throw new Error(
        `Blocked live network call in tests: ${url}. Mock this dependency instead.`,
      );
    }
    return realFetch(input, init);
  }) as typeof fetch;
}

/** Postgres connection string. Required — the app fails fast without it. */
export const DATABASE_URL = env.DATABASE_URL ?? "";

/**
 * Bootstrap credentials for the very first account + user (created when the
 * database is empty). Subsequent users are created via the signup/join UI.
 */
export const APP_EMAIL = env.APP_EMAIL ?? "";

/** Bootstrap password (see APP_EMAIL). */
export const APP_PASSWORD = env.APP_PASSWORD ?? "";

/** Secret used to sign the session cookie. Required — the app fails fast without it. */
export const SESSION_SECRET = env.SESSION_SECRET ?? "";

/** The app's receipts address — the single address for the receipts-by-email
 * feature: users forward receipts TO it (shown in Settings, used in the
 * verification-email copy) and, when FastMail sending is configured,
 * replies/verifications are sent FROM it (identity-matched against the
 * account; the account's default identity is used when unset). The FastMail
 * delivery rule must file mail to this address into RECEIPTS_FOLDER. */
export const INBOUND_EMAIL_ADDRESS = env.INBOUND_EMAIL_ADDRESS ?? "";

/**
 * FastMail API token — the JMAP push inbox reader (replaces the Resend
 * inbound webhook as the receipt source when set; the webhook stays as a
 * fallback). Optional — when unset, the push/cron routes return 503 and
 * receipts keep flowing through Resend.
 */
export const FASTMAIL_TOKEN = env.FASTMAIL_TOKEN ?? "";

/** Private P-256 key for RFC 8291 push decryption (base64url) — generated by `pnpm setup:push`. */
export const PUSH_PRIVATE_KEY = env.PUSH_PRIVATE_KEY ?? "";

/** 16-byte auth secret for RFC 8291 push decryption (base64url) — generated by `pnpm setup:push`. */
export const PUSH_AUTH = env.PUSH_AUTH ?? "";

/**
 * Stable id for this app's FastMail push subscription. Keep it distinct from
 * other apps on the same FastMail account (inbox uses `usps-digest-cleaner`)
 * so renewals never touch someone else's subscription.
 */
export const DEVICE_CLIENT_ID = env.DEVICE_CLIENT_ID || "expense-receipts";

/**
 * Name of the FastMail folder the delivery rule files receipt mail into
 * (Settings → Rules). The processor queries only this folder and destroys
 * emails after a successful import, so receipts never land in the Inbox.
 */
export const RECEIPTS_FOLDER = env.RECEIPTS_FOLDER || "Receipts";

/**
 * Secret gating the daily FastMail cron (GET /api/inbound-cron). Vercel
 * sends cron requests with `Authorization: Bearer <CRON_SECRET>` when the
 * env var is set; the route rejects everything else. Optional — the cron
 * route 503s without it.
 */
export const CRON_SECRET = env.CRON_SECRET ?? "";

/** DeepSeek API key — parses receipt text and (when supported) OCRs images. */
export const DEEPSEEK_API_KEY = env.DEEPSEEK_API_KEY ?? "";

/** DeepSeek model id (default: deepseek-v4-flash). */
export const DEEPSEEK_MODEL = env.DEEPSEEK_MODEL || "deepseek-v4-flash";

/**
 * OCR backend for image/scanned receipts:
 *  - "auto"     try DeepSeek vision first, fall back to local tesseract OCR
 *  - "deepseek" DeepSeek vision only (errors are reported back)
 *  - "tesseract"local OCR only
 */
export const RECEIPT_OCR_MODE = (env.RECEIPT_OCR_MODE || "auto") as
  | "auto"
  | "deepseek"
  | "tesseract";

/**
 * Max image width sent to the DeepSeek vision call. Image tokens scale
 * with pixels², and receipts are text-heavy — 768px reads fine while
 * costing ~44% fewer vision tokens than the 1024px stored image. The
 * stored/displayed image is untouched (still STORED_IMAGE_MAX_WIDTH).
 * Tune down if extraction quality ever suffers on dense receipts, up if a
 * receipt comes back under-recognized.
 */
export const RECEIPT_VISION_MAX_WIDTH = clampInt(
  env.RECEIPT_VISION_MAX_WIDTH,
  384,
  1536,
  768,
);

/**
 * Secret gating GET /api/smoke (post-deploy PDF+OCR health check). Requests
 * must send it in the `x-smoke-secret` header; when unset the route is
 * disabled (404). `scripts/deploy` uses it after every production deploy.
 */
export const SMOKE_TEST_SECRET = env.SMOKE_TEST_SECRET ?? "";

/**
 * Public base URL the OAuth metadata advertises (issuer + endpoints) instead
 * of deriving it from each request. Set it when the app sits behind a
 * TLS-terminating proxy (e.g. a local https://expense.localhost setup) so
 * clients see the public origin, not the proxy-internal one. Optional.
 */
export const PUBLIC_URL = env.PUBLIC_URL ?? "";

/** Parse an integer env var, clamped to [min, max], with a fallback when
 * unset or unparseable. */
function clampInt(
  raw: string | undefined,
  min: number,
  max: number,
  fallback: number,
): number {
  const n = Number(raw);
  if (!Number.isInteger(n)) return fallback;
  return Math.min(max, Math.max(min, n));
}
