allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
  "@prisma/client": true
  "@prisma/engines": true
  prisma: true
  tesseract.js: true
  "@sentry/cli": set this to true or false
  "@sentry/node-cpu-profiler": set this to true or false

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - "@prisma/client"
  - "@prisma/engines"
  - prisma

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.7
  vite-plus: 0.2.7
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
patchedDependencies:
  tesseract.js@7.0.0: patches/tesseract.js@7.0.0.patch
