#!/usr/bin/env bash

set -eo pipefail

echo -e "\033[0;32m--- Generate Prisma client ---\033[0m"
prisma generate

echo -e "\033[0;32m--- Generate types for route modules ---\033[0m"
react-router typegen

echo -e "\033[0;32m--- Run format, lint, and type checks ---\033[0m"
vp check --fix
